name: ndialog
description: Dialog material widget with blur background and popup animation
version: 3.0.0
homepage: https://github.com/nizwar/ndialog

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

