name: ndialog
description: Dialog material widget with blur background and popup animation
version: 3.1.0
homepage: https://github.com/nizwar/ndialog

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter

