name: ndialog
description: Dialog material widget with blur background and popup animation
version: 1.2.1
homepage: https://github.com/nizwar
author: Nizwar <nizwar@merahputih.id>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.3 
