name: ndialog
description: Custom native dialog style with blur background, popup animation and ProgressDialog.
version: 4.1.1
homepage: https://github.com/nizwar/ndialog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter

